spring:
  profiles:
    active: dev
  application:
    name: base
---
server: 
  #应用都端口号
  port: 8081
spring:
  profiles: dev
  #服务器名称
  application.name: base
  datasource:
  #第一个数据库的配置
    master:  
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springcloud
      username: root
      #由于数据库没有设置密码，所以不需要密码
      #password: 123456
   #第二个数据库的配置
    slaver: 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springcloudslave
      username: root
      #password: 123456
    initialSize: 6
    minIdle: 20
    maxActive: 50
    
#引入打印日志输出配置采用了backlog日志记录的方式
logging: 
  config: classpath:logback-spring.xml
      
#注册到eureka服务上
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
#设置eureka心跳的周期（生产上不需要用这个配置）
  instance:
    lease-renewal-interval-in-seconds: 5
      
mybatis:
  mapper-locations: classpath*:com/junly/**/mapper/*.xml
  
---
server: 
  #应用都端口号
  port: 8082
spring:
  profiles: test
  #服务器名称
  application.name: base
  datasource:
  #第一个数据库的配置
    master:  
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springcloud
      username: root
      #由于数据库没有设置密码，所以不需要密码
      #password: 123456
   #第二个数据库的配置
    slaver: 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springcloudslave
      username: root
      #password: 123456
    initialSize: 6
    minIdle: 20
    maxActive: 50
      
#引入打印日志输出配置采用了backlog日志记录的方式
logging: 
  config: classpath:logback-spring.xml
  
#注册到eureka服务上
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
mybatis:
  mapper-locations: classpath*:com/junly/**/mapper/*.xml
      