
#实现eureka的高可用配置，三个小横杠表示分割3个不同服务器的配置测试用！表示3台eureka互相注册实现高可用
spring: 
  profiles:
    active: peer3
---
server:
  port: 8762
spring:
  profiles: peer1
  application:
    name: eureka-ha1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8763/eureka/,http://peer3:8764/eureka/

---
server:
  port: 8763
spring:
  profiles: peer2
  application:
    name: eureka-ha2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer3:8764/eureka/
      
---
server:
  port: 8764
spring:
  profiles: peer3
  application:
    name: eureka-ha3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/